#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# https://github.com/desktop/desktop/issues/12562#issuecomment-1007154382
# npm.cmd run lint

export PATH=/Users/frida/.nvm/versions/node/v17.9.1/bin:$PATH
npx lint-staged

npm run build